CREATE TABLE "Users" (
  "user_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(255) UNIQUE NOT NULL,
  "password_hash" varchar(255) NOT NULL
);

CREATE TABLE "Channels" (
  "channel_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "channel_name" varchar(255) UNIQUE NOT NULL
);

CREATE TABLE "Rooms" (
  "room_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "room_name" varchar(255) NOT NULL,
  "channel_id" int
);

CREATE TABLE "Messages" (
  "message_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "content" text NOT NULL,
  "sender_id" int,
  "room_id" int,
  "timestamp" timestamptz DEFAULT (CURRENT_TIMESTAMP),
  "is_read" boolean DEFAULT false
);

ALTER TABLE "Messages" ADD FOREIGN KEY ("sender_id") REFERENCES "Users" ("user_id");

ALTER TABLE "Messages" ADD FOREIGN KEY ("room_id") REFERENCES "Rooms" ("room_id");

ALTER TABLE "Rooms" ADD FOREIGN KEY ("channel_id") REFERENCES "Channels" ("channel_id");
