DO $$DECLARE
    r RECORD;
BEGIN
    FOR r IN (SELECT tablename FROM pg_tables WHERE schemaname = current_schema()) LOOP
        EXECUTE 'DROP TABLE IF EXISTS ' || quote_ident(r.tablename) || ' CASCADE';
    END LOOP;
END$$;

CREATE TABLE Users (
    ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Avatar BYTEA DEFAULT decode('iVBORw0KGgoAAAANSUhEUgAAAEsAAABNCAMAAADZyWnFAAAAOVBMVEXo6epXWFrs7e37+/zz8/Pv7/D+/v5ZWlz29vb5+fm/wMFiYmTh4uPV1teoqaptbnCFhoh5eXuVlpdyR7wwAAAD/ElEQVRYw61Yi5KDIAxETBQQ8fH/H3sJ0Ko14erNMXWcUdkmYVmSmMFbGMD2Pd2c9QMiPXGnJz1i7/gJ5idAT+h2n9Wj8R6cd0A38A7d6cYXWERjrKWftQAWXp/eZ3kwmjkDWrDmcxAg2+ktDmzreRb2BpxzfNUb1BuAUYa1+P70OsuI8WLHWoMtE+IFHwbR7xegbBzcZoE74tX7sljefDUQLrNyvHrPy4DeI68I3awx36LhxzoyVl+wenqK5sF4zSIOAuGQj8zEvNC0PvYJFC8pzxqyKcwJpl+hKAiEMvQoxpjvomV1Ml/mRFEnfBzDvm7btqYQlQU9ccK9hxSqsE5dGdOWZtGyA8Dk3cDAQqxiIqQxD4ZbgmjZaw8NJjtMlxCreR0rUsWbksyNGu4aL/Q3KDuv3QWKxhSkJci6xPEqtPL3YMX1E4nGkqIU/0L1iiUs4S5A0dglsIpVfBRWcBKxulGKGTOVdZVj/6WHGWyZpfAXXWVOfG0Wg+2CYS7rBJNMwEoalGyYzVxlFRX+aFWxxjEJ/110FbzwKm46luik5b1tRax5aWBt0jYvuioJTRNLChipDxpZ3+NjLMu6KopcXJ9iGdZVWTD3p/EiJ80gnhY26FDiOuakQzkuWqQI8hRQzgSTGsHfxXgZb+QcpMWJsUuiAahgtVxUndR8bHFimhUkBavBifEfsRSu6j62gr+bhyPptJ/NMx/VHdlNQU2G1Bey4ms7qI1FeYkU9zTrSDqWFSzrdv17jfdlLW9YnbJ9ql0trDsv2litDPW2lLSI+tde09X8R7cDV5HUenYruqqIa7e2kmoD+GAhW+RCp5xD5e0nVpOodA559z922VzDNJh/o9eqxh4856samJ23OyeSahf5iODlEzIGSfMn5RCyNV/FO4PjzBWHqBMLlzNWzL+EvDCGtC5jpyWsVM7sYb7C2aOGubiWNq6BGkcav10Y7pqvDh959JzWX4AucNG+82j3rmEq0q67Jsr1WipByr1qDeNr3THv0wOgYt24hVPdUWoYAiU2PUN6q5B91chDLZgxjH8ZvBVK/8jjq370PnV/A9sM3HpDzTSp5ePRG3pXy6CXQC2oBEe9feoNPQcjKDz3hk79ifDQTXawluuu1DCn3tBDXizh6Chh7Q29+zkQ9/FbsG5c59zIefWG8KM35IES6O4rXpEswrs3BLU39GpWVmvj+sVWYqMus269oWorJTi/aA5tQ/THLHf0hm6dvxgatrEWBuilfqGThsc5LeNdyKpsWS/OOnpD1/5qP2SBHbvzGFmdSVkGL8zKZ20hm78GLoeABTu3v7ZlW9c9BYr3JUyXOINp96M9kcVENJHqORwGlie1H21/AGSVWyPVNNOeAAAAAElFTkSuQmCC', 'base64'),
    Username varchar(255) UNIQUE NOT NULL,
    Password varchar(255) NOT NULL,
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Channels (
    ID SERIAL PRIMARY KEY,
    Name VARCHAR(255) NOT NULL
);

CREATE TABLE Rooms (
    ID SERIAL PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    ChannelID INT NOT NULL,
    FOREIGN KEY (ChannelID) REFERENCES Channels(ID) ON DELETE CASCADE
);

CREATE TABLE Messages (
    ID SERIAL PRIMARY KEY,
    RoomID INT NOT NULL,
    SenderID INT NOT NULL, -- Assuming SenderID is a reference to Users.ID
    Content TEXT,
    Timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    IsRead BOOLEAN,
    FOREIGN KEY (RoomID) REFERENCES Rooms(ID) ON DELETE CASCADE,
    FOREIGN KEY (SenderID) REFERENCES Users(ID)
);

CREATE TABLE ChannelsToUsers (
    user_id INT,
    channel_id INT,
    PRIMARY KEY (user_id, channel_id),
    FOREIGN KEY (user_id) REFERENCES Users(ID) ON DELETE CASCADE,
    FOREIGN KEY (channel_id) REFERENCES Channels(ID) ON DELETE CASCADE
);

CREATE TABLE RoomsToChannels (
    room_id INT,
    channel_id INT,
    PRIMARY KEY (room_id, channel_id),
    FOREIGN KEY (room_id) REFERENCES Rooms(ID) ON DELETE CASCADE,
    FOREIGN KEY (channel_id) REFERENCES Channels(ID) ON DELETE CASCADE
);

CREATE INDEX idx_username_users ON Users (Username);
CREATE INDEX idx_room_id_rooms ON Rooms (ID);
CREATE INDEX idx_room_id_messages ON Messages (RoomID);

CREATE INDEX idx_user_id_users_to_channels ON ChannelsToUsers (user_id);
CREATE INDEX idx_room_id_rooms_to_channels ON RoomsToChannels (room_id);
CREATE INDEX idx_channel_id_rooms_to_channels ON RoomsToChannels (channel_id);
